name: Initialization

on:
  push: 
    branches: main

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Docker buil checkout
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & Push Docker Image
        with:
          image: cristianmorenoweb/spring-app
          registry: docker.hub
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
