name: Building app

on:
  push:
    branches: [master]
  workflow_run:
    workflows: [main]
    types: [completed]

jobs:
  download-and-build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    services:
      postgres:
        image: postgres:17.0-alpine3.20
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: 
          - 5432:5432
        volumes:
          - db_volume:/var/lib/postgresql/data
    steps:
      - name: Downloading artifact...
        id: artifact
        uses: actions/download-artifact@v4
        with:
          name: app
          path: app 
      - name: View files...
        run: ls
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Check app running...
        id: curl
        run: |
          curl localhost:8080/actuator/health
      - if: ${{ failure() && steps.curl.conclusion == 'failure' }}
        name: Running application
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: |
          echo Curl result: ${{ steps.curl.conclusion }}
          java -jar app/app.jar
      - if: ${{ success() && steps.curl.conclusion == 'success' }}
        name: Check app is running...
        run: echo Java started command has been omitted because it is are already running...