name: App

on:
  push: 
    branches: [master]

jobs:
  simple-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21
          cache: maven
      - run: mvn clean install
      - run: mkdir -p spring-app && cp target/app.jar spring-app
      - uses: actions/upload-artifact@v4
        with: 
          name: app
          path: spring-app
      
  docker-push:
    runs-on: ubuntu-latest
    needs: [simple-job]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: app
          path: spring-app
      - run: ls -d **/*

      - uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: cristianmorenoweb/spring-app
          tags: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}