name: Main

on:
  push:
    branches: [master]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checking repository...
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Executing maven...
        run: mvn clean package
      - name: Uploading artifact...
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: target/app.jar

  download-and-build:
    runs-on: ubuntu-latest
    needs: [build-and-upload]
    services:
      postgres:
        image: postgres:17.0-alpine3.20
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: 
          - 5432:5432
    steps:
      - name: Downloading artifact...
        uses: actions/download-artifact@v4
        with:
          name: app
          path: app
      - name: View files...
        run: ls
        
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Running application
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        run: |
          java -jar app/app.jar
    
        
      

    


        