name: main

on:
  push:
    branches: [master]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checking repository...
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Executing maven...
        run: mvn clean package
      - name: Uploading artifact...
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: target/app.jar
      

    


        