name: App

on:
  push: 
    branches: [master]

jobs:
  create-artifact:
    runs-on: ubuntu-latest
    container: maven:latest
    steps:
      - name: Checking repository...
        uses: actions/checkout@v4
      - name: Installing dependencies...
        run: mvn clean install
      - name: Creating directory...
        run: mkdir -p spring-artifact
      - name: Copy jar in artifact...
        run: cp target/app.jar spring-artifact
      - name: Uploading artifact... 
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: spring-artifact

      